driver:
  name: hyperv
  parent_vhd_folder: C:\src\hyperv\WIN2012r2WMF5
  parent_vhd_name: WIN2012r2_WMF5.vhd
  boot_iso_path: C:\src\kitchens\TestScript\Unattendxml.iso
  #iso_path: C:\src\kitchens\TestScript\other.iso
  memory_startup_bytes: 1073741824
  vm_switch: inet
  #ip_address: 192.168.111.109
  #subnet: 255.255.255.0
transport:
  name: winrm
  username: Administrator
  password: P@ssw0rd

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
      #configuration_mode_frequency_mins: 30
      #debug_mode: none
    configuration_script_folder: examples
    configuration_script: dsc_configuration.ps1
    #modules_path: .

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: WIN2012r2_WMF5
    driver:
      parent_vhd: C:\src\hyperv\WIN2012R2\WIN2012r2_WMF5.vhd
    provisioner:
      dsc_local_configuration_manager_version: wmf5
  
suites:
  - name: default
  #https://github.com/test-kitchen/kitchen-dsc